version: 2

sources:
  - name: person
    description: "Dados brutos extraídos do banco de dados PostgreSQL da Adventure Works."
    schema: sap_adw
    tables:
      - name: "emailaddress"
        description: "Tabela contendo o email das pessoas."
        columns:
          - name: "businessentityid"
            description: "Chave primária. Pessoa associada a este endereço de e-mail. Chave estrangeira para Person.BusinessEntityID"

          - name: "emailaddressid"
            description: "Chave primária. ID deste endereço de e-mail."

          - name: "emailaddress"
            description: "Endereço de e-mail da pessoa."

      - name: "address"
        description: "Tabela com informações de endereço de clientes, funcionários e fornecedores."
        columns:
          - name: "addressid"
            description: "Chave primária para registros de endereço."
            tests:
              - unique
              - not_null

          - name: "addressline1"
            description: "Primeira linha de endereço."

          - name: "addressline2"
            description: "Segunda linha de endereço."

          - name: "city"
            description: "Nome da cidade."

          - name: "stateprovinceid"
            description: "Número de identificação exclusivo do estado ou província. Chave estrangeira para a tabela StateProvince."
            tests:
              - unique
              - not_null

          - name: "postalcode"
            description: "Código postal do endereço."

          - name: "spatiallocation"
            description: "Latitude e longitude do endereço."

      - name: "stateprovince"
        description: "Tabela de consulta de estado e província."
        columns:
          - name: "stateprovinceid"
            description: "Chave primária para registros StateProvince."
            tests:
              - unique
              - not_null

          - name: "stateprovincecode"
            description: "Código padrão de estado ou província ISO."

          - name: "countryregioncode"
            description: "Código padrão de país ou região ISO. Chave estrangeira para CountryRegion.CountryRegionCode."

          - name: "isonlystateprovinceflag"
            description: "Status do stateprovince: 0 = StateProvinceCode existe. 1 = StateProvinceCode indisponível, usando CountryRegionCode."

          - name: "name"
            description: "Descrição do estado ou província."

          - name: "territoryid"
            description: "ID do território em que o estado ou província está localizado. Chave estrangeira para SalesTerritory.SalesTerritoryID."

      - name: "countryregion"
        description: "Tabela de consulta contendo os códigos padrão ISO para países e regiões."
        columns:
          - name: "countryregioncode"
            description: "Código do país/região."

          - name: "name"
            description: "Nome do país/região."

      - name: "person"
        description: "Tabela contendo informações das pessoas envolvidas com AdventureWorks: funcionários, contatos de clientes e contatos de fornecedores."
        columns:
          - name: "businessentityid"
            description: "Chave primária para registros Pessoa."
            tests:
              - unique
              - not_null

          - name: "persontype"
            description: "Tipo principal de pessoa: SC = Contato da loja, IN = Cliente individual (varejo), SP = Vendedor, EM = Funcionário (não relacionado a vendas), VC = Contato do fornecedor, GC = Contato geral"

          - name: "namestyle"
            description: "0 = Os dados em Nome e Sobrenome são armazenados na ordem de estilo ocidental (nome, sobrenome). 1 = Ordem de estilo oriental (sobrenome, nome)."

          - name: "namestyle"
            description: "0 = Os dados em Nome e Sobrenome são armazenados na ordem de estilo ocidental (nome, sobrenome). 1 = Ordem de estilo oriental (sobrenome, nome)."

          - name: "title"
            description: "Um título de cortesia. Por exemplo, Sr. ou Sra."

          - name: "firstname"
            description: "Primeiro nome da pessoa."

          - name: "middlename"
            description: "Nome do meio ou inicial do meio da pessoa."

          - name: "lastname"
            description: "Sobrenome da pessoa."

          - name: "suffix"
            description: "Sufixo de sobrenome. Por exemplo, Sr. ou Jr."

          - name: "emailpromotion"
            description: "Deseja receber promoção por email: 0 = O contato não deseja receber promoções por e-mail, 1 = O contato deseja receber promoções por e-mail da AdventureWorks, 2 = O contato deseja receber promoções por e-mail da AdventureWorks e de parceiros selecionados."

          - name: "additionalcontactinfo"
            description: "Informações adicionais de contato sobre a pessoa armazenadas em formato xml."

          - name: "demographics"
            description: "Informações pessoais, como hobbies e receitas coletadas de compradores on-line. Usado para análise de vendas."