version: 2

sources:
  - name: production
    description: Dados brutos extraídos do banco de dados PostgreSQL da Adventure Works.
    schema: sap_adw
    tables:
      - name: "product"
        description: "Tabela com informações dos produtos vendidos ou utilizados na fabricação de produtos vendidos."
        columns:
          - name: "productid"
            description: "Chave primária para registros de produtos."
            tests:
              - unique
              - not_null

          - name: "name"
            description: "Nome do produto."

          - name: "productnumber"
            description: "Número de identificação exclusivo do produto."

          - name: "makeflag"
            description: "Origem do Produto: 0 = O produto é adquirido, 1 = O produto é fabricado internamente."

          - name: "finishedgoodsflag"
            description: "Vendável: 0 = O produto não é um item vendável. 1 = O produto é vendável."

          - name: "color"
            description: "Cor do produto."

          - name: "safetystocklevel"
            description: "Quantidade mínima de estoque."

          - name: "reorderpoint"
            description: "Nível de estoque que aciona um pedido de compra ou ordem de serviço."

          - name: "standardcost"
            description: "Custo padrão do produto."

          - name: "listprice"
            description: "Preço de venda."

          - name: "size"
            description: "Tamanho do produto."

          - name: "sizeunitmeasurecode"
            description: "Unidade de medida da coluna Tamanho."

          - name: "weightunitmeasurecode"
            description: "Unidade de medida da coluna Peso."

          - name: "weight"
            description: "Peso do Produto."

          - name: "daystomanufacture"
            description: "Número de dias necessários para fabricar o produto."

          - name: "productline"
            description: "Linha do produto: R = Estrada, M = Montanha, T = Touring, S = Padrão."

          - name: "class"
            description: "Classe do produto: H = Alto, M = Médio, L = Baixo."

          - name: "style"
            description: "Tipo do produto: W = Feminino, M = Masculino, U = Universal."

          - name: "productsubcategoryid"
            description: "Subcategoria do produto. Chave estrangeira para ProductSubCategory.ProductSubCategoryID."
            tests:
              - unique
              - not_null

          - name: "productmodelid"
            description: "Modelo de produto. Chave estrangeira para ProductModel.ProductModelID."
            tests:
              - unique
              - not_null

          - name: "sellstartdate"
            description: "Data em que o produto estava disponível para venda."

          - name: "sellenddate"
            description: "Data em que o produto não estava mais disponível para venda."

          - name: "discontinueddate"
            description: "Data em que o produto foi descontinuado."

      - name: "productsubcategory"
        description: "Subcategorias de produtos. Consulte a tabela ProductCategory."
        columns:
          - name: "productsubcategoryid"
            description: "Chave primária para registros ProductSubcategory."
            tests:
              - unique
              - not_null

          - name: "productcategoryid"
            description: "Número de identificação da categoria do produto. Chave estrangeira para ProductCategory.ProductCategoryID."
            tests:
              - unique
              - not_null

          - name: "name"
            description: "Descrição da subcategoria."

      - name: "productcategory"
        description: "Tabela com informações com a categorização de alto nível dos produtos."
        columns:
          - name: "productcategoryid"
            description: "Chave primária para registros ProductCategory."
            tests:
              - unique
              - not_null

          - name: "name"
            description: "Descrição da categoria."
            tests:
              - unique
              - not_null
